# -*- coding: utf-8 -*-
"""NN1validate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_bKqB1t7X57wEUcBT11S_ZTRMZCRoYD
"""

#mounting google driv
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#change directory 
# %cd /content/drive/MyDrive/DMV

import numpy as np
from sklearn.neural_network import MLPClassifier

# Load training data
train_data = np.loadtxt("atriskstudentstrain.csv", delimiter=",", skiprows=1)
X_train = train_data[:, :-1]
y_train = train_data[:, -1]

# Load test data
test_data = np.loadtxt("atriskstudentstest.csv", delimiter=",", skiprows=1)
X_test = test_data[:, :-1]
y_test = test_data[:, -1]

# Create a multi-layer NN with 1 hidden layer and 10 neurons
clf = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', max_iter=1000)

# Train the NN
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Compute the mean squared error
mse = np.mean((y_test - y_pred)**2)
print(f"Mean squared error: {mse:.3f}")